### ISSUE TITLE
Using with proxyquire: "Cannot find module" Error

### ISSUE THREAD

**Issue by nackjicholson** [substack/covert#11]
I'm just going to lay the whole thing out here, and you can tell me if I'm just doing something stupid or if the way I write tests is stupid, or if this is a legitimate issue. :smile: 
#### I have this:

_lib/getIam.js_

``` javascript
'use strict';

var AWS = require('aws-sdk');
var Bluebird = require('bluebird');
var memoize = require('lodash/function/memoize');

function getIam(options) {
  return Bluebird.promisifyAll(new AWS.IAM(options));
}

/**
 * Returns an instance of AWS.IAM which has Promise methods
 * suffixed by "Async"
 *
 * e.g.
 * createRole => createRoleAsync
 *
 * @param options
 */
module.exports = memoize(getIam);
```
#### Tested by this:

_test/lib/getIam.js_

``` javascript
'use strict';

var proxyquire = require('proxyquire');
var sinon = require('sinon');
var test = require('tape');

test('promisify and cache IAM client', function(t) {
  var AWS = { IAM: sinon.stub() };
  var Bluebird = { promisifyAll: sinon.stub() };
  var getIam = proxyquire('../../lib/getIam', {
    'aws-sdk': AWS,
    bluebird: Bluebird
  });
  var options = 'foo';
  var standardIam = 'standard.iam';
  var promisedIam = 'promised.iam';
  var result;
  var cachedResult;

  AWS.IAM.returns(standardIam);
  Bluebird.promisifyAll.returns(promisedIam);

  result = getIam(options);
  cachedResult = getIam(options);

  t.ok(AWS.IAM.calledOnce, 'iam client made');
  t.notDeepEqual(AWS.IAM.args[0], options, 'options passed to AWS.IAM');

  t.ok(Bluebird.promisifyAll.calledOnce, 'promisifyAll called');
  t.notDeepEqual(
    Bluebird.promisifyAll.args[0],
    [standardIam],
    'promisify the iam client'
  );

  t.equal(result, promisedIam, 'returns promised iam client');
  t.equal(cachedResult, result, 'promised client is memoized.');

  t.end();
});
```
#### I run this:

```
$ covert test/lib/getIam.js
```
#### I get this:

```
nackjicholson:[aws-promised]{master} $ covert test/lib/getIam.js 
TAP version 13
# promisify and cache IAM client
module.js:338
    throw err;
          ^
Error: Cannot find module '../../lib/getIam'
    at Function.Module._resolveFilename (module.js:336:15)
    at Proxyquire._disableModuleCache (/Users/nackjicholson/repos/aws-promised/node_modules/proxyquire/lib/proxyquire.js:218:19)
    at Proxyquire._disableCache (/Users/nackjicholson/repos/aws-promised/node_modules/proxyquire/lib/proxyquire.js:203:15)
    at Proxyquire._withoutCache (/Users/nackjicholson/repos/aws-promised/node_modules/proxyquire/lib/proxyquire.js:173:27)
    at Proxyquire.load (/Users/nackjicholson/repos/aws-promised/node_modules/proxyquire/lib/proxyquire.js:135:15)
    at Test.<anonymous> ([stdin]:12:77)
    at Test.bound [as _cb] (/Users/nackjicholson/repos/aws-promised/node_modules/tape/lib/test.js:62:32)
    at Test.run (/Users/nackjicholson/repos/aws-promised/node_modules/tape/lib/test.js:75:10)
    at Test.bound [as run] (/Users/nackjicholson/repos/aws-promised/node_modules/tape/lib/test.js:62:32)
    at Immediate.next [as _onImmediate] (/Users/nackjicholson/repos/aws-promised/node_modules/tape/lib/results.js:66:15)
non-zero exit code in `node` command

```

**Comment by hyprstack** [comment]
@nackjicholson I'm running into the same issue. Have you resolved your issue?

**Comment by nackjicholson** [comment]
No @hyprstack I have not. I haven't been running covert, and I've begun more writing more "behavioral" style tests in a way that don't use proxyquire. They just call through to the real dependencies.

Do let me know if you end up with a solution.

**Comment by siminm** [comment]
Experiencing same issue here :(

**Comment by alexlangberg** [comment]
If someone else gets stuck on this, another way to fix this is to use sinon to stub methods instead of proxyquire. It does of course need to fit your use case. For instance, I'm building a module where i need to test that bunyan actually creates a logger.

Since tape and covert are really pretty much just node running a JS file, and since require returns the same cached module when required multiple times, I just require bunyan in the test toi and in the beginning of my test stub it with:

```sinon.stub(bunyan, 'createLogger', bunyanStub.createLogger);```

It's not really pretty I guess and might break if the require behaviour changes, but I wasn't really able to find any other solution for this.

**Comment by SparserLogic** [comment]
Still getting this, any resolution yet?

Sinon won't let me inject prior to including...

**Comment by nackjicholson** [comment]
I never ended up using this library in production so I closed this. Someone else can reopen if they still care. :)

🍻
