### ISSUE TITLE
issues with __filename / __dirname

### ISSUE THREAD

**Issue by tmpvar** [substack/covert#12]
here's a test case that exercises the `__filename` aspect of this issue

```javascript
var test = require('tape');
var fs = require('fs');

test('expose bug', function(t) {
  fs.readFile(__filename, function(e, c) {
    t.error(e);
    t.ok(c.length > 0);
    t.end();
  });
});
```

when run with node/tape:

```
tmp‣ node covert-test.js
TAP version 13
# expose bug
ok 1 null
ok 2 (unnamed assert)

1..2
# tests 2
# pass  2

# ok
```

when run with covert:

```
tmp‣ covert covert-test.js
TAP version 13
# expose bug
not ok 1 Error: ENOENT, open '[stdin]'
  ---
    operator: error
    expected:
      undefined
    actual:
      { [Error: ENOENT, open '[stdin]'] errno: 34, code: 'ENOENT', path: '[stdin]' }
    stack:
      Error: ENOENT, open '[stdin]'
  ...

/Users/tmpvar/work/js/tmp/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Cannot read property 'length' of undefined
    at [stdin]:10:90
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
non-zero exit code in `node` command
```

**Comment by arhart** [comment]
This is consistent with the behavior when running from stdin.

```
~/node/covert-issues-12$ cat covert-test.js | node
TAP version 13
# expose bug
not ok 1 Error: ENOENT, open '[stdin]'
  ---
    operator: error
    expected:
      undefined
    actual:
      { [Error: ENOENT, open '[stdin]'] errno: 34, code: 'ENOENT', path: '[stdin]' }
    stack:
      Error: ENOENT, open '[stdin]'
  ...

[stdin]:7
    t.ok(c.length > 0);
          ^
TypeError: Cannot read property 'length' of undefined
    at [stdin]:7:11
    at fs.js:208:20
    at Object.oncomplete (fs.js:108:15)
```

However, current browserify should support making this work as if not running from stdin: https://github.com/substack/browserify-handbook#__filename
